# Generated by Django 6.0.6 on 2026-06-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='total_airtime_earned',
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_withdrawn_naira',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total Naira successfully withdrawn to bank', max_digits=10),
        ),
    ]
