"""
Management command: python manage.py seed_extra
Adds 130+ extra questions across existing and NEW categories.
Safe to re-run — skips already-existing questions.
"""
from django.core.management.base import BaseCommand
from apps.quiz.models import Category, Question, Answer


NEW_CATEGORIES = [
    {'name': 'Sports & Entertainment', 'icon': '⚽', 'subs': ['Nigerian Football', 'Nollywood & Music']},
    {'name': 'Business & Economics',   'icon': '💼', 'subs': []},
    {'name': 'Health & Wellness',      'icon': '🏥', 'subs': []},
    {'name': 'Geography & Travel',     'icon': '🗺️', 'subs': []},
]

# Format: (question_text, [(answer, is_correct), ...], difficulty, explanation)
EXTRA_QUESTIONS = {

    # ═══════════════════════════════════════════════
    # MATHEMATICS — 15 more
    # ═══════════════════════════════════════════════
    'Mathematics': [
        ('What is the perimeter of a square with side 9cm?',
         [('36cm', True), ('18cm', False), ('81cm', False), ('27cm', False)], 'easy',
         '4 × 9 = 36cm'),
        ('What is 45% of 500?',
         [('225', True), ('250', False), ('200', False), ('215', False)], 'easy',
         '45/100 × 500 = 225'),
        ('What is the next prime number after 13?',
         [('17', True), ('15', False), ('14', False), ('16', False)], 'easy',
         '14=2×7, 15=3×5, 16=2⁴, 17 is prime'),
        ('What is 3/5 of 200?',
         [('120', True), ('100', False), ('130', False), ('110', False)], 'easy',
         '3/5 × 200 = 120'),
        ('A rectangle has length 15cm and width 8cm. What is its area?',
         [('120cm²', True), ('46cm²', False), ('108cm²', False), ('90cm²', False)], 'easy',
         'Area = 15 × 8 = 120cm²'),
        ('What is the value of 5! (5 factorial)?',
         [('120', True), ('60', False), ('24', False), ('100', False)], 'medium',
         '5! = 5×4×3×2×1 = 120'),
        ('If the ratio of boys to girls is 3:5 and there are 24 boys, how many girls are there?',
         [('40', True), ('30', False), ('35', False), ('45', False)], 'medium',
         '3 parts = 24, so 1 part = 8, girls = 5×8 = 40'),
        ('What is the gradient of the line y = 5x − 3?',
         [('5', True), ('-3', False), ('3', False), ('−5', False)], 'medium',
         'y = mx + c, gradient m = 5'),
        ('Simplify: (2x³)(3x²)',
         [('6x⁵', True), ('5x⁵', False), ('6x⁶', False), ('6x', False)], 'medium',
         '2×3 = 6, x³×x² = x⁵'),
        ('What is the median of: 3, 7, 2, 9, 5, 1, 8?',
         [('5', True), ('7', False), ('3', False), ('6', False)], 'medium',
         'Sorted: 1,2,3,5,7,8,9 — middle value is 5'),
        ('Two angles of a triangle are 55° and 75°. Find the third.',
         [('50°', True), ('60°', False), ('70°', False), ('45°', False)], 'medium',
         '180 − 55 − 75 = 50°'),
        ('What is the volume of a cube with side 4cm?',
         [('64cm³', True), ('48cm³', False), ('16cm³', False), ('32cm³', False)], 'hard',
         'V = s³ = 4³ = 64cm³'),
        ('Find x if 2ˣ = 64',
         [('6', True), ('8', False), ('5', False), ('7', False)], 'hard',
         '2⁶ = 64, so x = 6'),
        ('What is the sum of the first 10 natural numbers?',
         [('55', True), ('50', False), ('45', False), ('60', False)], 'medium',
         'n(n+1)/2 = 10×11/2 = 55'),
        ('A bag has 4 red and 6 blue balls. Probability of picking red?',
         [('2/5', True), ('4/10', False), ('1/3', False), ('3/5', False)], 'hard',
         '4/10 = 2/5'),
    ],

    # ═══════════════════════════════════════════════
    # SCIENCE — 15 more
    # ═══════════════════════════════════════════════
    'Science': [
        ('What is the powerhouse of the cell?',
         [('Mitochondria', True), ('Ribosome', False), ('Nucleus', False), ('Vacuole', False)], 'easy',
         'Mitochondria produce ATP energy'),
        ('What is the freezing point of water in Celsius?',
         [('0°C', True), ('100°C', False), ('-10°C', False), ('32°C', False)], 'easy',
         'Water freezes at 0°C (32°F)'),
        ('What gas makes up most of Earth\'s atmosphere?',
         [('Nitrogen (78%)', True), ('Oxygen', False), ('Carbon dioxide', False), ('Argon', False)], 'easy',
         'Nitrogen makes up ~78% of the atmosphere'),
        ('What is the chemical symbol for iron?',
         [('Fe', True), ('Ir', False), ('In', False), ('Io', False)], 'easy',
         'Fe comes from Latin Ferrum'),
        ('Which vitamin does sunlight provide?',
         [('Vitamin D', True), ('Vitamin A', False), ('Vitamin C', False), ('Vitamin B12', False)], 'easy',
         'Sunlight triggers Vitamin D synthesis in the skin'),
        ('What is the most abundant element in the Earth\'s crust?',
         [('Oxygen', True), ('Silicon', False), ('Iron', False), ('Aluminium', False)], 'medium',
         'Oxygen makes up ~46% of Earth\'s crust by mass'),
        ('What is osmosis?',
         [('Movement of water across a semi-permeable membrane from low to high solute concentration',
           True),
          ('Movement of solutes across a membrane', False),
          ('Conversion of glucose to energy', False),
          ('Absorption of minerals by plant roots', False)], 'medium',
         'Osmosis is passive water movement down its concentration gradient'),
        ('Which organ in the human body produces insulin?',
         [('Pancreas', True), ('Liver', False), ('Kidney', False), ('Thyroid', False)], 'medium',
         'The pancreas produces insulin to regulate blood sugar'),
        ('What is the SI unit of force?',
         [('Newton', True), ('Joule', False), ('Watt', False), ('Pascal', False)], 'medium',
         'Force is measured in Newtons (N)'),
        ('What is photosynthesis\' overall equation?',
         [('6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂', True),
          ('C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O', False),
          ('2H₂ + O₂ → 2H₂O', False),
          ('CO₂ + H₂O → CH₂O + O₂', False)], 'hard',
         'Light energy converts CO₂ and water into glucose and oxygen'),
        ('What is Ohm\'s Law?',
         [('V = IR (Voltage = Current × Resistance)', True),
          ('P = IV (Power = Current × Voltage)', False),
          ('F = ma', False),
          ('E = mc²', False)], 'medium',
         'Voltage equals current multiplied by resistance'),
        ('Which blood type is the universal donor?',
         [('O negative (O−)', True), ('AB positive', False), ('A positive', False), ('B negative', False)], 'medium',
         'O− can be given to anyone regardless of blood type'),
        ('What is the function of white blood cells?',
         [('Fight infection and disease', True),
          ('Carry oxygen around the body', False),
          ('Help blood clot', False),
          ('Produce hormones', False)], 'easy',
         'White blood cells (leukocytes) are part of the immune system'),
        ('What is the half-life concept?',
         [('Time for half of a radioactive substance to decay', True),
          ('Time for a substance to fully decompose', False),
          ('Half the atomic weight of an element', False),
          ('Time for a reaction to reach equilibrium', False)], 'hard',
         'Half-life is constant for each radioactive isotope'),
        ('What is Newton\'s Third Law?',
         [('Every action has an equal and opposite reaction', True),
          ('Force equals mass times acceleration', False),
          ('Objects at rest stay at rest', False),
          ('Energy cannot be created or destroyed', False)], 'easy',
         'For every action, there is an equal and opposite reaction'),
    ],

    # ═══════════════════════════════════════════════
    # GENERAL KNOWLEDGE — 15 more
    # ═══════════════════════════════════════════════
    'General Knowledge': [
        ('What is the largest country in Africa by area?',
         [('Algeria', True), ('Sudan', False), ('DR Congo', False), ('Libya', False)], 'medium',
         'Algeria covers 2.38 million km²'),
        ('Who invented the telephone?',
         [('Alexander Graham Bell', True), ('Thomas Edison', False), ('Nikola Tesla', False), ('Guglielmo Marconi', False)], 'easy',
         'Bell patented the telephone in 1876'),
        ('What is the currency of South Africa?',
         [('Rand', True), ('Shilling', False), ('Naira', False), ('Dollar', False)], 'easy',
         'The South African Rand (ZAR)'),
        ('How many players are on a football (soccer) team on the pitch?',
         [('11', True), ('10', False), ('12', False), ('9', False)], 'easy',
         '11 players per side on the pitch'),
        ('What does "INEC" stand for in Nigeria?',
         [('Independent National Electoral Commission', True),
          ('International National Electoral Committee', False),
          ('Independent Nigerian Electoral Commission', False),
          ('Institute of National Electoral Conduct', False)], 'easy',
         'INEC manages Nigerian elections'),
        ('Which Nigerian state is known as the food basket of the nation?',
         [('Benue', True), ('Kano', False), ('Plateau', False), ('Kaduna', False)], 'medium',
         'Benue State is Nigeria\'s largest producer of food crops'),
        ('What is the official language of Egypt?',
         [('Arabic', True), ('French', False), ('English', False), ('Coptic', False)], 'easy',
         'Modern Standard Arabic is Egypt\'s official language'),
        ('Who was the first person to walk on the moon?',
         [('Neil Armstrong', True), ('Buzz Aldrin', False), ('Yuri Gagarin', False), ('John Glenn', False)], 'easy',
         'Neil Armstrong walked on the moon on July 20, 1969'),
        ('What is the name of Nigeria\'s national airline?',
         [('Air Nigeria (now defunct — replaced by Nigeria Air)', True),
          ('Arik Air', False), ('Dana Air', False), ('Green Africa', False)], 'medium',
         'Nigeria has attempted several national airlines'),
        ('Which city is known as the "Kano of the South" or commercial hub of eastern Nigeria?',
         [('Onitsha', True), ('Enugu', False), ('Aba', False), ('Port Harcourt', False)], 'medium',
         'Onitsha is famous for its massive international market'),
        ('What is the world\'s most visited country by tourists?',
         [('France', True), ('Spain', False), ('USA', False), ('China', False)], 'hard',
         'France consistently tops global tourism rankings'),
        ('What does ASUU stand for in Nigeria?',
         [('Academic Staff Union of Universities', True),
          ('Association of Senior University Unions', False),
          ('Academic Staff Unified Union', False),
          ('Academic Staff Union of Undergraduates', False)], 'easy',
         'ASUU represents university lecturers in Nigeria'),
        ('Which West African country was formerly called Gold Coast?',
         [('Ghana', True), ('Ivory Coast', False), ('Senegal', False), ('Togo', False)], 'medium',
         'Ghana was renamed from Gold Coast at independence in 1957'),
        ('Who wrote the Nigerian national anthem currently in use?',
         [('A national committee', True), ('Chinua Achebe', False), ('Wole Soyinka', False), ('Fela Kuti', False)], 'hard',
         'The current anthem was written by a collective and adopted in 1978'),
        ('The Niger River flows through Nigeria and empties into which body of water?',
         [('Atlantic Ocean (Gulf of Guinea)', True),
          ('Lake Chad', False),
          ('Indian Ocean', False),
          ('Mediterranean Sea', False)], 'medium',
         'The Niger Delta flows into the Gulf of Guinea'),
    ],

    # ═══════════════════════════════════════════════
    # TECHNOLOGY — 12 more
    # ═══════════════════════════════════════════════
    'Technology': [
        ('What does "USB" stand for?',
         [('Universal Serial Bus', True), ('United System Bus', False), ('Universal System Bridge', False), ('Unified Serial Bus', False)], 'easy',
         'USB is the standard connector for peripherals'),
        ('What programming language is primarily used for Android development?',
         [('Kotlin (and Java)', True), ('Swift', False), ('Python', False), ('C#', False)], 'medium',
         'Google recommends Kotlin for Android; Java is also widely used'),
        ('What does "LAN" stand for?',
         [('Local Area Network', True), ('Large Area Node', False), ('Local Access Node', False), ('Long Area Network', False)], 'easy',
         'A LAN connects devices within a limited area like a building'),
        ('Which company created React.js?',
         [('Facebook (Meta)', True), ('Google', False), ('Microsoft', False), ('Twitter', False)], 'medium',
         'React was developed by Facebook and released in 2013'),
        ('What is the purpose of a CDN (Content Delivery Network)?',
         [('Deliver web content faster by serving from servers close to the user', True),
          ('Protect websites from DDoS attacks', False),
          ('Store database backups', False),
          ('Encrypt data in transit', False)], 'medium',
         'CDNs reduce latency by caching content near users'),
        ('What does "JSON" stand for?',
         [('JavaScript Object Notation', True), ('Java System Object Node', False), ('JavaScript Open Node', False), ('Java Serialized Object Notation', False)], 'medium',
         'JSON is a lightweight data-interchange format'),
        ('What is the difference between RAM and ROM?',
         [('RAM is temporary (loses data on power off); ROM is permanent', True),
          ('RAM is read-only; ROM is writable', False),
          ('ROM is faster than RAM', False),
          ('RAM stores the operating system permanently', False)], 'medium',
         'RAM = volatile memory. ROM = non-volatile/permanent storage'),
        ('What is "cloud computing"?',
         [('Delivery of computing services (storage, servers, software) over the internet', True),
          ('Computing using weather data', False),
          ('A type of wireless network', False),
          ('Storing files on your local hard drive', False)], 'easy',
         'Cloud computing enables on-demand access to IT resources'),
        ('Which Nigerian company is known as a leading fintech and payment platform?',
         [('Paystack', True), ('Flutterwave', False), ('Both are correct', True), ('GTBank', False)], 'easy',
         'Both Paystack and Flutterwave are major Nigerian fintechs'),
        ('What does "SaaS" stand for?',
         [('Software as a Service', True), ('System as a Service', False), ('Software and Security', False), ('Server as a Solution', False)], 'medium',
         'SaaS delivers software over the internet on subscription'),
        ('What is Git used for?',
         [('Version control — tracking changes to code', True),
          ('Running web servers', False),
          ('Writing HTML', False),
          ('Managing databases', False)], 'easy',
         'Git tracks code history and enables team collaboration'),
        ('What is the function of an IP address?',
         [('Uniquely identifies a device on a network', True),
          ('Encrypts internet traffic', False),
          ('Speeds up internet connection', False),
          ('Stores website data', False)], 'easy',
         'Every device on a network has a unique IP address'),
    ],

    # ═══════════════════════════════════════════════
    # AFRICAN HISTORY & CULTURE — 12 more
    # ═══════════════════════════════════════════════
    'African History & Culture': [
        ('What is the name of Nigeria\'s legislative body?',
         [('National Assembly', True), ('Parliament', False), ('Senate only', False), ('Congress', False)], 'easy',
         'Nigeria\'s National Assembly consists of the Senate and House of Representatives'),
        ('Who was the first Prime Minister of Nigeria?',
         [('Tafawa Balewa', True), ('Nnamdi Azikiwe', False), ('Obafemi Awolowo', False), ('Abubakar Tafawa', False)], 'easy',
         'Sir Abubakar Tafawa Balewa was Nigeria\'s first and only PM'),
        ('The Igbo "Ozo" title is associated with which concept?',
         [('Prestige and social achievement', True), ('Military rank', False), ('Age group', False), ('Religious position', False)], 'medium',
         'Ozo is a prestigious chieftaincy title in Igboland'),
        ('What is Jollof Rice Wars a friendly rivalry between?',
         [('Nigeria and Ghana', True), ('Nigeria and Senegal', False), ('Ghana and Cameroon', False), ('Nigeria and Ivory Coast', False)], 'easy',
         'The Jollof Wars is a social media rivalry between Nigeria and Ghana over whose Jollof is better'),
        ('Which ancient trading empire was located in modern-day Mali and Mauritania?',
         [('Ghana Empire', True), ('Mali Empire', False), ('Songhai Empire', False), ('Kanem-Bornu', False)], 'medium',
         'The Ghana Empire (not related to modern Ghana) was a major gold trading state'),
        ('Who is known as the "Father of African Nationalism"?',
         [('Kwame Nkrumah', True), ('Jomo Kenyatta', False), ('Julius Nyerere', False), ('Nelson Mandela', False)], 'hard',
         'Kwame Nkrumah championed Pan-Africanism and Ghanaian independence'),
        ('The Yoruba New Year celebration is called?',
         [('Odun Tuntun', True), ('Oshun Festival', False), ('Oro Festival', False), ('Egungun', False)], 'hard',
         'Odun Tuntun marks the Yoruba new year'),
        ('Which Nigerian city is famous for the groundnut pyramids?',
         [('Kano', True), ('Kaduna', False), ('Sokoto', False), ('Maiduguri', False)], 'medium',
         'Kano\'s groundnut pyramids were a symbol of Nigeria\'s agricultural wealth'),
        ('What does "ECOWAS" seek to achieve in West Africa?',
         [('Economic integration and free movement of people and goods', True),
          ('Military alliance against external threats', False),
          ('A single currency immediately', False),
          ('Joint educational curriculum', False)], 'medium',
         'ECOWAS promotes regional economic integration'),
        ('Which Afrobeats artist is known as the "King of Afrobeats"?',
         [('Wizkid (also Fela Kuti for Afrobeat)', True), ('Burna Boy', False), ('Davido', False), ('Tekno', False)], 'medium',
         'Wizkid is widely called King of Afrobeats; Fela Kuti pioneered Afrobeat'),
        ('What is the name of the highest mountain in Nigeria?',
         [('Chappal Waddi', True), ('Jos Plateau', False), ('Shebshi Mountains', False), ('Mandara Mountains', False)], 'hard',
         'Chappal Waddi in Taraba State stands at 2,419m'),
        ('The Oba is the traditional ruler of which Nigerian group?',
         [('Yoruba', True), ('Igbo', False), ('Hausa', False), ('Ijaw', False)], 'easy',
         'Oba is the Yoruba title for king or ruler'),
    ],

    # ═══════════════════════════════════════════════
    # AI & CYBERSECURITY — 10 more
    # ═══════════════════════════════════════════════
    'AI & Cybersecurity': [
        ('What is "deep learning"?',
         [('A type of machine learning using multi-layered neural networks', True),
          ('Learning that takes a very long time', False),
          ('AI that learns by reading books', False),
          ('A method of encrypting data', False)], 'medium',
         'Deep learning uses many layers of neural networks to learn complex patterns'),
        ('What is a "trojan horse" in cybersecurity?',
         [('Malware disguised as legitimate software', True),
          ('A type of network attack', False),
          ('A secure login method', False),
          ('An antivirus program', False)], 'medium',
         'Like the myth, it appears harmless but contains malicious code'),
        ('What is "natural language processing" (NLP)?',
         [('AI ability to understand and generate human language', True),
          ('A programming language for AI', False),
          ('Translating machine code to English', False),
          ('Speech-to-text conversion only', False)], 'medium',
         'NLP powers chatbots, translation, and text analysis'),
        ('What does "CAPTCHA" stand for?',
         [('Completely Automated Public Turing test to tell Computers and Humans Apart', True),
          ('Computer Automated Program To Check Human Access', False),
          ('Coded Authentication Protocol To Control Human Access', False),
          ('Central Access Protocol for Technology Control and Human Authentication', False)], 'hard',
         'CAPTCHAs verify that the user is human, not a bot'),
        ('What is "multi-factor authentication"?',
         [('Using two or more verification methods to confirm identity', True),
          ('Having multiple passwords', False),
          ('Using fingerprint only', False),
          ('Logging in from multiple devices', False)], 'easy',
         'MFA combines something you know, have, and are'),
        ('What is "overfitting" in machine learning?',
         [('When a model learns training data too well and performs poorly on new data', True),
          ('When a model is trained with too much data', False),
          ('When training takes too long', False),
          ('When a model is too simple', False)], 'hard',
         'Overfitting = memorising rather than generalising'),
        ('What is "social engineering" in cybersecurity?',
         [('Manipulating people into revealing confidential information', True),
          ('Building secure social media platforms', False),
          ('Using AI to manage social networks', False),
          ('Analysing social media data', False)], 'medium',
         'Social engineering exploits human psychology rather than technical vulnerabilities'),
        ('Which Nigerian law governs cybercrime in Nigeria?',
         [('Cybercrimes (Prohibition, Prevention, etc.) Act 2015', True),
          ('Digital Crimes Act 2012', False),
          ('Nigeria Internet Security Act 2018', False),
          ('Technology Misuse Act 2010', False)], 'hard',
         'The 2015 Cybercrime Act criminalises hacking, fraud, and cyber harassment in Nigeria'),
        ('What is "tokenisation" in AI?',
         [('Breaking text into smaller units (tokens) for processing', True),
          ('Generating cryptocurrency tokens', False),
          ('Encrypting authentication data', False),
          ('Converting images to numbers', False)], 'hard',
         'LLMs process text by splitting it into tokens before analysis'),
        ('What is a "brute force attack"?',
         [('Trying every possible password combination until the correct one is found', True),
          ('Physically damaging a server', False),
          ('Overloading a network with traffic', False),
          ('Injecting code into a website', False)], 'easy',
         'Brute force attacks are prevented by account lockouts and complex passwords'),
    ],

    # ═══════════════════════════════════════════════
    # CURRENT AFFAIRS — 10 more
    # ═══════════════════════════════════════════════
    'Current Affairs': [
        ('What is the name of Nigeria\'s current central bank digital currency?',
         [('eNaira', True), ('DigiNaira', False), ('CryptoNaira', False), ('NairaX', False)], 'easy',
         'The eNaira launched in October 2021, making Nigeria one of the first countries with a CBDC'),
        ('What does "PVC" stand for in Nigerian elections?',
         [('Permanent Voter\'s Card', True), ('Pre-Verified Card', False), ('Permanent Voting Certificate', False), ('Personal Voter\'s Card', False)], 'easy',
         'The PVC is required to vote in Nigerian elections'),
        ('Which Nigerian state was the first to establish a technology hub?',
         [('Lagos', True), ('Abuja', False), ('Rivers', False), ('Oyo', False)], 'medium',
         'Lagos (Yaba) is Nigeria\'s Silicon Valley'),
        ('What is the name of Africa\'s largest free trade agreement?',
         [('African Continental Free Trade Area (AfCFTA)', True),
          ('ECOWAS Trade Agreement', False),
          ('Pan-African Trade Union', False),
          ('African Union Trade Pact', False)], 'medium',
         'AfCFTA came into force in 2021'),
        ('Which company became the first African startup to achieve a $1 billion valuation (unicorn)?',
         [('Interswitch (Nigeria)', True), ('Jumia', False), ('Flutterwave', False), ('Andela', False)], 'hard',
         'Interswitch became Africa\'s first fintech unicorn around 2019'),
        ('What does "PMS" stand for in the Nigerian fuel context?',
         [('Premium Motor Spirit (petrol)', True), ('Petroleum Motor Supply', False), ('Public Motor Service', False), ('Primary Motor Spirit', False)], 'easy',
         'PMS is the technical term for regular petrol in Nigeria'),
        ('Which Nigerian tech founder is known as "Africa\'s Bill Gates"?',
         [('Strive Masiyiwa (Zimbabwe) or Aliko Dangote for business', True),
          ('Jason Njoku', False),
          ('Sim Shagaya', False),
          ('Herbert Wigwe', False)], 'hard',
         'Strive Masiyiwa (Econet founder) is often called Africa\'s Bill Gates'),
        ('What is the name of Nigeria\'s sovereign wealth fund?',
         [('Nigeria Sovereign Investment Authority (NSIA)', True),
          ('Nigerian National Investment Fund', False),
          ('Federal Investment Reserve of Nigeria', False),
          ('Central Investment Authority of Nigeria', False)], 'hard',
         'NSIA manages Nigeria\'s sovereign wealth'),
        ('Which city hosted the Africa Cup of Nations (AFCON) final in 2023?',
         [('Abidjan, Ivory Coast', True), ('Accra, Ghana', False), ('Cairo, Egypt', False), ('Rabat, Morocco', False)], 'medium',
         'AFCON 2023 was hosted by Ivory Coast'),
        ('What percentage of Nigerians have access to the internet (approx. 2024)?',
         [('Around 45–55%', True), ('Around 20–30%', False), ('Around 70–80%', False), ('Around 10%', False)], 'hard',
         'Nigeria has significant internet penetration but gaps remain in rural areas'),
    ],

    # ═══════════════════════════════════════════════
    # SPORTS & ENTERTAINMENT — 25 questions (NEW)
    # ═══════════════════════════════════════════════
    'Sports & Entertainment': [
        ('Which country has won the most FIFA World Cups?',
         [('Brazil (5 times)', True), ('Germany', False), ('Italy', False), ('Argentina', False)], 'easy',
         'Brazil won in 1958, 1962, 1970, 1994, and 2002'),
        ('Who is Nigeria\'s most capped international footballer?',
         [('Ahmed Musa', True), ('Jay-Jay Okocha', False), ('Kanu Nwankwo', False), ('Vincent Enyeama', False)], 'medium',
         'Ahmed Musa holds the record for most Super Eagles appearances'),
        ('What year did Nigeria first qualify for the FIFA World Cup?',
         [('1994 (USA)', True), ('1990', False), ('1998', False), ('2002', False)], 'medium',
         'Nigeria made their World Cup debut at USA 1994'),
        ('Which Afrobeats song became the first Nigerian song to hit 1 billion streams on Spotify?',
         [('Essence by Wizkid ft. Tems', True), ('Fall by Davido', False), ('Ye by Burna Boy', False), ('Skeleton by Burna Boy', False)], 'medium',
         'Essence achieved this milestone in 2022'),
        ('What does "Nollywood" refer to?',
         [('Nigeria\'s film industry', True), ('A streaming platform', False), ('A Nigerian Hollywood studio', False), ('A Bollywood sub-genre', False)], 'easy',
         'Nollywood is the world\'s second-largest film producer by volume'),
        ('Who holds the record for the most Olympic gold medals?',
         [('Michael Phelps (23 gold medals)', True), ('Usain Bolt', False), ('Carl Lewis', False), ('Mark Spitz', False)], 'medium',
         'Michael Phelps won 23 gold medals across four Olympic Games'),
        ('Which Nigerian singer is known as "Odogwu"?',
         [('Burna Boy', True), ('Wizkid', False), ('Davido', False), ('Tekno', False)], 'easy',
         '"Odogwu" is one of Burna Boy\'s most popular songs and a nickname'),
        ('What is the nickname of the Nigerian national football team?',
         [('Super Eagles', True), ('Green Eagles', False), ('African Eagles', False), ('Nigeria Warriors', False)], 'easy',
         'The Super Eagles have represented Nigeria since 1994'),
        ('In which sport would you perform a "slam dunk"?',
         [('Basketball', True), ('Volleyball', False), ('American Football', False), ('Rugby', False)], 'easy',
         'A slam dunk involves jumping and putting the ball through the basket'),
        ('Which Nigerian musician popularised Afrobeat (the original genre)?',
         [('Fela Kuti', True), ('King Sunny Ade', False), ('Ebenezer Obey', False), ('Victor Olaiya', False)], 'easy',
         'Fela Anikulapo Kuti created Afrobeat, blending jazz, funk, and African music'),
        ('How many gold medals did Nigeria win at the 1996 Atlanta Olympics?',
         [('1 (football)', True), ('0', False), ('3', False), ('2', False)], 'hard',
         'Nigeria\'s Super Eagles won gold at Atlanta 1996, defeating Argentina 3-2'),
        ('Who is the all-time top scorer in the English Premier League?',
         [('Alan Shearer', True), ('Wayne Rooney', False), ('Andrew Cole', False), ('Frank Lampard', False)], 'hard',
         'Alan Shearer scored 260 Premier League goals'),
        ('What does "Grammy" stand for?',
         [('Gramophone Award', True), ('Grand Recording and Musical Merit Award', False), ('Grammy is not an acronym', True), ('Great Recording Award for Music and Media', False)], 'hard',
         'Grammy is short for Gramophone — the award is shaped like one'),
        ('Which Nigerian artist won the Grammy for Best Global Music Album in 2023?',
         [('Burna Boy', True), ('Wizkid', False), ('Davido', False), ('Femi Kuti', False)], 'medium',
         'Burna Boy won his second Grammy in 2023 for "I Told Them..."'),
        ('What is the highest-grossing Nollywood film of all time?',
         [('A Tribe Called Judah (2024)', True), ('The Wedding Party', False), ('King of Boys', False), ('Living in Bondage', False)], 'hard',
         'A Tribe Called Judah broke Nollywood box office records'),
        ('How long is a standard football (soccer) match?',
         [('90 minutes', True), ('80 minutes', False), ('100 minutes', False), ('75 minutes', False)], 'easy',
         '90 minutes in two 45-minute halves, plus injury time'),
        ('Which Nigerian state is home to most Nollywood productions?',
         [('Lagos', True), ('Enugu', False), ('Anambra', False), ('Abuja', False)], 'easy',
         'Lagos is the centre of the Nigerian film industry'),
        ('What sport does Serena Williams play?',
         [('Tennis', True), ('Badminton', False), ('Squash', False), ('Table Tennis', False)], 'easy',
         'Serena Williams is one of the greatest tennis players of all time'),
        ('What is the name of the trophy awarded to the English Premier League champions?',
         [('Premier League Trophy', True), ('FA Cup', False), ('The Shield', False), ('Champions Trophy', False)], 'medium',
         'The Premier League Trophy is presented to the season champions'),
        ('Which Nigerian comedian is known as "AY"?',
         [('Ayodeji Richard Makun', True), ('Alibek Saitov', False), ('Adebayo Salami', False), ('Ayo Makun', False)], 'medium',
         'AY (Ayodeji Makun) is one of Nigeria\'s biggest comedians'),
        ('What is the length of a standard Olympic swimming pool?',
         [('50 metres', True), ('25 metres', False), ('100 metres', False), ('75 metres', False)], 'medium',
         'Olympic pools are 50m long with 10 lanes'),
        ('In chess, which piece can only move diagonally?',
         [('Bishop', True), ('Knight', False), ('Rook', False), ('Queen', False)], 'easy',
         'The Bishop moves any number of squares diagonally'),
        ('What does "VAR" stand for in football?',
         [('Video Assistant Referee', True), ('Video Assisted Review', False), ('Virtual Assistant Referee', False), ('Video Action Replay', False)], 'easy',
         'VAR uses video technology to assist match officials'),
        ('Which Nigerian film director is known for "October 1" and "76"?',
         [('Kunle Afolayan', True), ('Kemi Adetiba', False), ('Genevieve Nnaji', False), ('Desmond Ovbiagele', False)], 'hard',
         'Kunle Afolayan is one of Nollywood\'s most acclaimed directors'),
        ('Which country won the 2023 Africa Cup of Nations?',
         [('Ivory Coast', True), ('Nigeria', False), ('Morocco', False), ('Egypt', False)], 'medium',
         'Ivory Coast won AFCON 2023 on home soil, beating Nigeria in the final'),
    ],

    # ═══════════════════════════════════════════════
    # BUSINESS & ECONOMICS — 20 questions (NEW)
    # ═══════════════════════════════════════════════
    'Business & Economics': [
        ('What does "GDP" stand for?',
         [('Gross Domestic Product', True), ('General Domestic Product', False), ('Gross Development Product', False), ('Government Domestic Production', False)], 'easy',
         'GDP measures the total value of goods and services produced in a country'),
        ('What is inflation?',
         [('A general increase in prices reducing purchasing power', True),
          ('An increase in government spending', False),
          ('The printing of more money only', False),
          ('A decrease in unemployment', False)], 'easy',
         'Inflation reduces what each unit of currency can buy'),
        ('What does "SME" stand for in business?',
         [('Small and Medium Enterprises', True), ('Standard Market Entity', False), ('Small Management Enterprise', False), ('State-Managed Economy', False)], 'easy',
         'SMEs are the backbone of most economies including Nigeria'),
        ('What is the role of Nigeria\'s Central Bank (CBN)?',
         [('Regulate monetary policy, currency, and banking system', True),
          ('Collect taxes from citizens', False),
          ('Manage government spending', False),
          ('Control stock market prices', False)], 'easy',
         'The CBN manages monetary policy and financial stability'),
        ('What is a "startup"?',
         [('A new company designed to grow rapidly with a scalable business model', True),
          ('Any new small business', False),
          ('A company that just started trading', False),
          ('A business with fewer than 10 employees', False)], 'medium',
         'Startups aim for rapid growth and are often tech-focused'),
        ('What is "venture capital"?',
         [('Investment in early-stage companies in exchange for equity', True),
          ('Loans from commercial banks', False),
          ('Government grants for businesses', False),
          ('Money raised from the public on stock markets', False)], 'medium',
         'VCs fund startups with high growth potential in exchange for ownership shares'),
        ('What does "IPO" stand for?',
         [('Initial Public Offering', True), ('Internal Public Offering', False), ('International Portfolio Option', False), ('Initial Private Offering', False)], 'medium',
         'An IPO is when a company offers shares to the public for the first time'),
        ('What is the Nigerian Stock Exchange now called?',
         [('NGX (Nigerian Exchange Group)', True), ('NSE', False), ('Lagos Stock Exchange', False), ('Nigerian Capital Market', False)], 'medium',
         'The NSE was rebranded to NGX in 2021'),
        ('What is "supply and demand"?',
         [('The relationship between availability of goods and consumer desire for them', True),
          ('How much a company supplies and demands from suppliers', False),
          ('The balance between import and export', False),
          ('The ratio of products to prices', False)], 'easy',
         'When demand exceeds supply, prices rise; when supply exceeds demand, prices fall'),
        ('What is "net profit"?',
         [('Revenue minus all costs and taxes', True),
          ('Total sales revenue', False),
          ('Revenue minus cost of goods only', False),
          ('Cash in the bank', False)], 'medium',
         'Net profit = total revenue − all expenses and taxes'),
        ('Which Nigerian conglomerate is the largest company in Africa by revenue?',
         [('Dangote Group', True), ('MTN Nigeria', False), ('Zenith Bank', False), ('NNPC', False)], 'medium',
         'Aliko Dangote\'s group spans cement, flour, sugar, and oil refinery'),
        ('What does "B2B" stand for?',
         [('Business to Business', True), ('Back to Base', False), ('Build to Business', False), ('Business to Buyer', False)], 'easy',
         'B2B companies sell products or services to other businesses'),
        ('What is a "balance sheet"?',
         [('A financial statement showing assets, liabilities, and equity at a point in time', True),
          ('A record of daily transactions', False),
          ('A summary of monthly profits', False),
          ('A comparison of income vs expenses', False)], 'medium',
         'Assets = Liabilities + Equity'),
        ('What does "ROI" stand for?',
         [('Return on Investment', True), ('Rate of Income', False), ('Revenue over Income', False), ('Return on Interest', False)], 'easy',
         'ROI measures the profitability of an investment'),
        ('What is "e-commerce"?',
         [('Buying and selling goods and services over the internet', True),
          ('Electronic currency exchange', False),
          ('Email-based marketing', False),
          ('Electronic company registration', False)], 'easy',
         'E-commerce platforms include Jumia, Konga, and Amazon'),
        ('Which payment method is most popular for e-commerce in Nigeria?',
         [('Bank transfer and card payment (via Paystack/Flutterwave)', True),
          ('Cash on delivery only', False),
          ('Cryptocurrency only', False),
          ('Cheque payments', False)], 'medium',
         'Digital payments have become dominant for Nigerian online shopping'),
        ('What is "diversification" in investment?',
         [('Spreading investments across different assets to reduce risk', True),
          ('Investing all money in one high-return asset', False),
          ('Moving all funds abroad', False),
          ('Selling all shares at once', False)], 'medium',
         'Don\'t put all your eggs in one basket'),
        ('What is Nigeria\'s most valuable export?',
         [('Crude oil', True), ('Cocoa', False), ('Natural gas', False), ('Agricultural products', False)], 'easy',
         'Oil accounts for over 90% of Nigeria\'s export revenue'),
        ('What does "fintech" mean?',
         [('Financial technology — using tech to improve financial services', True),
          ('Final technology stage in software development', False),
          ('Finance and technology degree', False),
          ('Federal internet network technology', False)], 'easy',
         'Fintech companies include Paystack, Kuda, PiggyVest, and OPay in Nigeria'),
        ('What is the main purpose of the Securities and Exchange Commission (SEC) in Nigeria?',
         [('Regulate the capital market and protect investors', True),
          ('Control interest rates', False),
          ('Issue Nigerian passports', False),
          ('Register new companies', False)], 'medium',
         'SEC Nigeria oversees the capital market and ensures fair trading'),
    ],

    # ═══════════════════════════════════════════════
    # HEALTH & WELLNESS — 15 questions (NEW)
    # ═══════════════════════════════════════════════
    'Health & Wellness': [
        ('How many litres of water should an average adult drink daily?',
         [('About 2–3 litres', True), ('1 litre', False), ('5 litres', False), ('0.5 litres', False)], 'easy',
         'The recommended intake is about 2–3 litres or 8 glasses per day'),
        ('What does "BMI" stand for?',
         [('Body Mass Index', True), ('Body Measurement Index', False), ('Basic Metabolic Indicator', False), ('Body Mass Indicator', False)], 'easy',
         'BMI = weight(kg) ÷ height²(m)'),
        ('What is malaria transmitted by?',
         [('Female Anopheles mosquito', True), ('Male mosquito', False), ('Tsetse fly', False), ('Contaminated water', False)], 'easy',
         'Plasmodium parasites are transmitted by the female Anopheles mosquito'),
        ('What is the function of the immune system?',
         [('Defend the body against infections and disease', True),
          ('Digest food and absorb nutrients', False),
          ('Pump blood around the body', False),
          ('Control hormone production', False)], 'easy',
         'The immune system identifies and destroys pathogens'),
        ('Which vitamin is essential for healthy eyesight and is found in carrots?',
         [('Vitamin A', True), ('Vitamin D', False), ('Vitamin C', False), ('Vitamin E', False)], 'easy',
         'Vitamin A deficiency causes night blindness'),
        ('What is "hypertension"?',
         [('High blood pressure', True), ('Low blood pressure', False), ('High blood sugar', False), ('Irregular heartbeat', False)], 'easy',
         'Hypertension (high BP) is a major risk factor for stroke and heart disease'),
        ('What is "diabetes mellitus"?',
         [('A metabolic disease where blood sugar is too high', True),
          ('An infection of the pancreas', False),
          ('A liver disease', False),
          ('A form of anaemia', False)], 'medium',
         'Type 1 = no insulin production. Type 2 = insulin resistance'),
        ('How many hours of sleep do adults typically need per night?',
         [('7–9 hours', True), ('5–6 hours', False), ('10–12 hours', False), ('4–5 hours', False)], 'easy',
         'The CDC recommends 7–9 hours for adults'),
        ('What is the normal human body temperature?',
         [('37°C (98.6°F)', True), ('36°C', False), ('38°C', False), ('35°C', False)], 'easy',
         'Normal body temperature is approximately 37°C'),
        ('What does "HIV" stand for?',
         [('Human Immunodeficiency Virus', True), ('Human Infection Virus', False), ('High Immunity Virus', False), ('Human Inflammatory Virus', False)], 'easy',
         'HIV attacks the immune system and can lead to AIDS if untreated'),
        ('What is the leading cause of death globally?',
         [('Cardiovascular (heart) disease', True), ('Cancer', False), ('Respiratory diseases', False), ('Diabetes', False)], 'medium',
         'Heart disease and stroke account for the most deaths globally'),
        ('What does "BMR" mean in health/fitness?',
         [('Basal Metabolic Rate — calories burned at complete rest', True),
          ('Body Mass Ratio', False),
          ('Basic Muscle Response', False),
          ('Body Movement Rate', False)], 'medium',
         'BMR is the minimum energy your body needs to function'),
        ('Which nutrient is the body\'s primary energy source?',
         [('Carbohydrates', True), ('Protein', False), ('Fat', False), ('Vitamins', False)], 'easy',
         'Carbohydrates are broken down into glucose for energy'),
        ('What is "cholesterol"?',
         [('A fatty substance in the blood — essential but harmful at high levels', True),
          ('A type of vitamin', False),
          ('A sugar found in the blood', False),
          ('A hormone produced by the kidneys', False)], 'medium',
         'High LDL cholesterol is a risk factor for heart disease'),
        ('How long should you wash your hands to remove germs effectively?',
         [('At least 20 seconds', True), ('5 seconds', False), ('1 minute', False), ('10 seconds', False)], 'easy',
         'The WHO recommends washing for at least 20 seconds with soap'),
    ],

    # ═══════════════════════════════════════════════
    # LOGIC & REASONING — 8 more
    # ═══════════════════════════════════════════════
    'Logic & Reasoning': [
        ('If all Lagosians are Nigerians, and Chioma is a Lagosian, is Chioma Nigerian?',
         [('Yes', True), ('No', False), ('Maybe', False), ('Cannot determine', False)], 'easy',
         'Simple syllogism: Lagosians → Nigerians, Chioma → Lagosian, therefore Chioma → Nigerian'),
        ('What is the missing number: 10, 20, 40, 80, ?',
         [('160', True), ('100', False), ('120', False), ('140', False)], 'easy',
         'Each number doubles: 80 × 2 = 160'),
        ('A shop sells 3 items for ₦900. How much for 7 items?',
         [('₦2,100', True), ('₦1,800', False), ('₦2,400', False), ('₦1,500', False)], 'easy',
         '₦900 ÷ 3 = ₦300 each. 7 × ₦300 = ₦2,100'),
        ('John is older than Mary. Mary is older than Sue. Who is the youngest?',
         [('Sue', True), ('Mary', False), ('John', False), ('Cannot tell', False)], 'easy',
         'John > Mary > Sue, therefore Sue is youngest'),
        ('A farmer has 17 sheep. All but 9 die. How many are left?',
         [('9', True), ('8', False), ('17', False), ('0', False)], 'medium',
         '"All but 9" means 9 survive'),
        ('What comes next: J, F, M, A, M, J, ?',
         [('J (July)', True), ('A (August)', False), ('S (September)', False), ('O (October)', False)], 'medium',
         'Months of the year: Jan, Feb, Mar, Apr, May, Jun, Jul'),
        ('If 6 workers build a wall in 10 days, how long for 3 workers (same rate)?',
         [('20 days', True), ('5 days', False), ('15 days', False), ('30 days', False)], 'medium',
         'Inverse proportion: fewer workers = more time. 6×10 ÷ 3 = 20'),
        ('Mary\'s mother has 4 children: Monday, Tuesday, Wednesday, and _?',
         [('Mary', True), ('Thursday', False), ('Friday', False), ('Sunday', False)], 'medium',
         'The question says "Mary\'s mother" — so the last child is Mary'),
    ],

}


class Command(BaseCommand):
    help = 'Add 130+ extra questions and new categories to TOPPERS.'

    def handle(self, *args, **options):
        self.stdout.write(self.style.MIGRATE_HEADING('\nAdding extra questions to TOPPERS...\n'))

        # ── New Categories ────────────────────────────────────
        self.stdout.write('Creating new categories...')
        for cat_data in NEW_CATEGORIES:
            parent, created = Category.objects.get_or_create(
                name=cat_data['name'],
                defaults={'icon': cat_data['icon']},
            )
            if created:
                self.stdout.write(f'  + {parent.name} {cat_data["icon"]}')
            for sub_name in cat_data.get('subs', []):
                sub, sc = Category.objects.get_or_create(
                    name=sub_name,
                    defaults={'parent': parent, 'icon': cat_data['icon']},
                )
                if sc:
                    self.stdout.write(f'    ↳ {sub_name}')

        # ── Extra Questions ───────────────────────────────────
        self.stdout.write('\nAdding questions...')
        total_new = 0
        total_skipped = 0

        for cat_name, questions in EXTRA_QUESTIONS.items():
            try:
                category = Category.objects.get(name=cat_name)
            except Category.DoesNotExist:
                self.stdout.write(self.style.WARNING(
                    f'  ⚠ Category "{cat_name}" not found — skipping'
                ))
                continue

            new = 0
            for text, answers, difficulty, explanation in questions:
                question, created = Question.objects.get_or_create(
                    text=text,
                    defaults={
                        'category': category,
                        'difficulty': difficulty,
                        'explanation': explanation,
                    },
                )
                if created:
                    for i, (ans_text, is_correct) in enumerate(answers):
                        Answer.objects.create(
                            question=question,
                            text=ans_text,
                            is_correct=is_correct,
                            order=i,
                        )
                    new += 1
                    total_new += 1
                else:
                    total_skipped += 1

            self.stdout.write(
                f'  {category.icon} {cat_name}: +{new} questions'
            )

        # ── Summary ───────────────────────────────────────────
        total_q = Question.objects.count()
        total_cats = Category.objects.count()

        self.stdout.write(self.style.SUCCESS(
            f'\n✅ Done!\n'
            f'   New questions added : {total_new}\n'
            f'   Already existed     : {total_skipped}\n'
            f'   Total questions now : {total_q}\n'
            f'   Total categories    : {total_cats}\n'
        ))
