# Generated by Django 6.0.6 on 2026-06-06 09:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('badge_emoji', models.CharField(default='🏆', max_length=10)),
                ('achievement_type', models.CharField(choices=[('streak', 'Streak'), ('games', 'Games Played'), ('score', 'Score'), ('referral', 'Referral'), ('accuracy', 'Accuracy'), ('level', 'Level'), ('category', 'Category'), ('special', 'Special')], max_length=20)),
                ('threshold', models.IntegerField(default=1, help_text='Value needed to unlock')),
                ('points_reward', models.IntegerField(default=0, help_text='Bonus points on unlock')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AirtimeRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('network', models.CharField(choices=[('mtn', 'MTN'), ('airtel', 'Airtel'), ('glo', 'Glo'), ('9mobile', '9Mobile')], max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('points_used', models.IntegerField()),
                ('naira_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('vtpass_reference', models.CharField(blank=True, max_length=100)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airtime_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(help_text='Positive = credit, negative = debit')),
                ('transaction_type', models.CharField(choices=[('earned_game', 'Earned from Game'), ('daily_bonus', 'Daily Login Bonus'), ('streak_bonus', 'Streak Bonus'), ('referral_bonus', 'Referral Bonus'), ('challenge_win', 'Challenge Win'), ('redeemed', 'Redeemed for Airtime'), ('ad_bonus', 'Ad Reward'), ('event_bonus', 'Event Bonus'), ('admin_credit', 'Admin Credit')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('balance_after', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transactions', to='games.gamesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='rewards.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
