# Generated by Django 6.0.6 on 2026-06-13 07:44

import apps.rewards.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='points_reward',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='threshold',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pointtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('earned_game', 'Earned from Game'), ('daily_bonus', 'Daily Login Bonus'), ('streak_bonus', 'Streak Bonus'), ('referral_bonus', 'Referral Bonus'), ('challenge_win', 'Challenge Win'), ('withdrawn', 'Withdrawn to Bank'), ('ad_bonus', 'Ad Reward'), ('event_bonus', 'Event Bonus'), ('admin_credit', 'Admin Credit')], max_length=30),
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_requested', models.DecimalField(decimal_places=2, help_text='Amount before fee', max_digits=10)),
                ('fee_amount', models.DecimalField(decimal_places=2, help_text='5% fee', max_digits=10)),
                ('amount_to_receive', models.DecimalField(decimal_places=2, help_text='Amount after fee deduction', max_digits=10)),
                ('points_deducted', models.IntegerField(help_text='Points deducted for this withdrawal')),
                ('bank_name', models.CharField(choices=[('access', 'Access Bank'), ('citibank', 'Citibank Nigeria'), ('ecobank', 'Ecobank Nigeria'), ('fcmb', 'FCMB'), ('fidelity', 'Fidelity Bank'), ('firstbank', 'First Bank of Nigeria'), ('gtbank', 'Guaranty Trust Bank (GTBank)'), ('heritage', 'Heritage Bank'), ('jaiz', 'Jaiz Bank'), ('keystone', 'Keystone Bank'), ('polaris', 'Polaris Bank'), ('providus', 'Providus Bank'), ('stanbic', 'Stanbic IBTC Bank'), ('sterling', 'Sterling Bank'), ('suntrust', 'SunTrust Bank'), ('titan', 'Titan Bank'), ('uba', 'United Bank for Africa (UBA)'), ('union', 'Union Bank'), ('unity', 'Unity Bank'), ('wema', 'Wema Bank'), ('zenith', 'Zenith Bank'), ('carbon', 'Carbon (One Finance)'), ('fairmoney', 'FairMoney Microfinance Bank'), ('kuda', 'Kuda Bank'), ('moniepoint', 'Moniepoint Microfinance Bank'), ('opay', 'OPay Digital Services'), ('palmpay', 'PalmPay'), ('rubies', 'Rubies Bank'), ('vfd', 'VFD Microfinance Bank'), ('branch', 'Branch International Finance'), ('eyowo', 'Eyowo')], max_length=50)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('reference', models.CharField(default=apps.rewards.models.generate_withdrawal_ref, max_length=30, unique=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AirtimeRedemption',
        ),
    ]
