# Generated by Django 6.0.6 on 2026-06-06 09:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('global', 'Global'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('period_key', models.CharField(default='all', max_length=20)),
                ('points', models.IntegerField(default=0)),
                ('games_played', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('challenges_won', models.IntegerField(default=0)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['period', 'rank'],
                'unique_together': {('user', 'period', 'period_key')},
            },
        ),
    ]
