# Generated by Django 6.0.6 on 2026-06-06 09:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('advertiser', models.CharField(blank=True, max_length=200)),
                ('ad_type', models.CharField(choices=[('video', 'Video'), ('banner', 'Banner'), ('interstitial', 'Interstitial')], max_length=20)),
                ('media_url', models.URLField(blank=True)),
                ('duration_seconds', models.IntegerField(default=30)),
                ('reward_type', models.CharField(choices=[('extra_game', 'Extra Game Session'), ('bonus_points', 'Bonus Points'), ('lifeline', 'Temporary Lifeline')], max_length=20)),
                ('reward_value', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('max_views_per_user_per_day', models.IntegerField(default=5)),
                ('total_views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reward_granted', models.BooleanField(default=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views_log', to='advertisements.advertisement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
    ]
